db_url = "postgres://postgres:postgres@10.255.0.2/postgres"

[http_server]
listen = "0.0.0.0:8000"
upload_storage_path = ""
real_addr_header = ""
admin_prefix = "/super_admin"

[dns_server]
listen = ""
