db_url = "postgres://postgres:postgres@10.255.0.2/postgres"
storage_path = "/tmp/"

[http_server]
listen = "0.0.0.0:8000"
jwt_secret = "TEST_VALUE"     # empty means random value
jwt_expire_time = 259200      # 3 days
real_addr_header = ""
admin_prefix = "/super_admin"
max_log_file_zie = 3145728    # 3MB

[dns_server]
listen = ""
