services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: ccr.ccs.tencentyun.com/rmb122/xss-receiver-backend:latest
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./app_data:/app/storage
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
      image: ccr.ccs.tencentyun.com/rmb122/xss-receiver-frontend:latest
      ports:
        - 8002:80
      environment:
        ADMIN_PREFIX: bdcd988332ea7d19537d67607d7cb19aa09eb449
        BACKEND_URL: http://backend:8000
      depends_on: 
        - backend
      restart: unless-stopped
