services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    image: ccr.ccs.tencentyun.com/rmb122/xss-receiver-backend:latest
    ports:
      - 8002:8000
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./app_data:/app/storage
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
